export const LIST_COMPRAS = "LIST_COMPRAS"
export const LIST_COMPRAS_PENDING = "LIST_COMPRAS_PENDING"
export const LIST_COMPRAS_REJECTED = "LIST_COMPRAS_REJECTED"
export const LIST_COMPRAS_FULFILLED = "LIST_COMPRAS_FULFILLED"
