export const LIST_COMPRAS = "LIST_COMPRAS"
export const LIST_COMPRAS_PENDING = "LIST_COMPRAS_PENDING"
export const LIST_COMPRAS_REJECTED = "LIST_COMPRAS_REJECTED"
export const LIST_COMPRAS_FULFILLED = "LIST_COMPRAS_FULFILLED"

export const ADD_COMPRA = "ADD_COMPRA"
export const ADD_COMPRA_PENDING = "ADD_COMPRA_PENDING"
export const ADD_COMPRA_REJECTED = "ADD_COMPRA_REJECTED"
export const ADD_COMPRA_FULFILLED = "ADD_COMPRA_FULFILLED"
