export const LIST_PROVEEDOR = "LIST_PROVEEDOR"
export const LIST_PROVEEDOR_PENDING = "LIST_PROVEEDOR_PENDING"
export const LIST_PROVEEDOR_REJECTED = "LIST_PROVEEDOR_REJECTED"
export const LIST_PROVEEDOR_FULFILLED = "LIST_PROVEEDOR_FULFILLED"
